---
version: "3.8"
services:
  test:
    build:
      target: test
      context: .

  cli:
    image: ${COMMIT_IMAGE:-local/lb-info:cli}
    build:
      target: cli
      context: .
    environment:
      RD_OPTION_ENV: $RD_OPTION_ENV
      RD_OPTION_DEVICES: $RD_OPTION_DEVICES
      RD_OPTION_NAUTOBOT_URL: $RD_OPTION_NAUTOBOT_URL
      LOG_LEVEL: $RD_OPTION_LOG_LEVEL
    command: master.py
    tty: true
